<a href="https://colab.research.google.com/github/Wycology/deep_learning_course/blob/main/2_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <font color='green'><b> SATELLITE DATA FOR AGRICULTURAL ECONOMISTS</b></font>


<font color='blue'><b>THEORY AND PRACTICE</b></font>

**_MACHINE & DEEP LEARNING_**


*David Wuepper, Hadi Hadi, Wyclife Agumba Oluoch*

[Land Economics Group](https://www.ilr1.uni-bonn.de/en/research/research-groups/land-economics), University of Bonn, Bonn, Germany

---

# **Background**


---

`Tensor`, by definition, is the fundamental data structure used to store and manipulate data in `PyTorch`. Understanding `tensor` is paramount to understanding how `PyTorch` implements advanced functions for deep learning. At both preprocessing of input and postprocessing of output, you will be dealing with `tensor` in most cases. It is therefore important to understand what `tensor` are and operations on them. If you know `NumPy` then you are 100% good to take on `tensor`. Let us see how to create some `tensor`.

For us to have `tensor`, we need to load `PyTorch` library first.

In [1]:
import torch # Of course we need to have the PyTorch

We start with a simple `tensor` with just one digit.

In [2]:
x = torch.tensor(2) # Creates a tensor containing value 2.
x

tensor(2)

We can also create a `tensor` from a list of numbers as follows.

In [3]:
x = torch.tensor([1, 2, 3]) # Creates a tensor containing the values 1, 2, and 3 in the list.
x

tensor([1, 2, 3])

We can have `tensor` for list within list.

In [4]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]]) # Creates a 2 x 3 tensor.
x

tensor([[1, 2, 3],
        [4, 5, 6]])

We can also perform simple operations with `tensor` like addition.

In [5]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
y = torch.tensor([[7, 8, 9], [10, 11, 12]])
z = x + y
print(z)

tensor([[ 8, 10, 12],
        [14, 16, 18]])


We may be interested in knowing the shape of the `tensor`.

In [6]:
print(z.shape)

torch.Size([2, 3])


## **Creating `tensor`**

`torch.tensor` is the basic way to create the `tensor` data structure. However, there are many ways to achieve this as follows:

In [8]:
import numpy # We are importing this because we will create some tensors from numpy

In [9]:
# Create from preexisting arrays
x = torch.tensor([1, 2, 3]) # Creating from a list
print(x)


tensor([1, 2, 3])


In [10]:
x = torch.tensor((1, 2, 3)) # Creating from a tuple
print(x)

tensor([1, 2, 3])


In [11]:
x = torch.tensor(numpy.array([1, 2, 3])) # Creating from numpy array
print(x)

tensor([1, 2, 3])


Other than `tensor` that we specifically indicate the values it should hold, we can also create `tensor` in which we only specify their dimensions/rank.

In [12]:
w = torch.empty(2, 3) # Uninitialized, no one can predict the initial values
w

tensor([[5.4640e-05, 4.1296e-05, 2.1651e+23],
        [1.0979e-05, 3.1201e-18, 3.1360e+27]])

In [13]:
w = torch.zeros(2, 3) # All elements in the tensor initialized by 0.0
w

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [14]:
w = torch.ones(2, 3) # All elements initialized by 1.0
w

tensor([[1., 1., 1.],
        [1., 1., 1.]])

Sometimes we may want to initialize a `tensor` with random numbers. There are functions that can help us with such tasks as follows:

In [15]:
y = torch.rand(4, 5) # Creates a 4 x 5 tensor with elements from uniform distribution on the interval (0, 1)
y

tensor([[0.8418, 0.3298, 0.9768, 0.0707, 0.3640],
        [0.6385, 0.9551, 0.2330, 0.7469, 0.8732],
        [0.1216, 0.6281, 0.0420, 0.3550, 0.3747],
        [0.2140, 0.1895, 0.3865, 0.5344, 0.3880]])

In [16]:
y = torch.randn(4, 5) # Creates a 4 x 5 tensor with elements from normal distribution with mean 0 and variance of 1.
y

tensor([[-1.3413,  0.7833, -0.2912,  0.4531,  0.4691],
        [ 0.9453, -1.1535,  0.5099, -0.8825, -1.1839],
        [-1.6739,  0.3192,  0.4024,  0.1985, -1.4034],
        [ 0.0345,  0.6887,  1.1673,  0.2618,  0.8854]])

In [17]:
y = torch.randint(-5, 5, (2, 3)) # Creates a 2 x 3 tensor with elements drawn between 0 and 9
y

tensor([[ 4, -4, -4],
        [ 3,  3,  2]])

### **Data type and device**

Upon creating the `tensor`, it is possible and sometimes a good practice to assign them data type and device. This can be achieved as follows:

In [18]:
m = torch.rand((2, 3), dtype = torch.float32, device = 'cpu')
print(f"The tensor is of data type: {m.dtype} and on {m.device} device.")

The tensor is of data type: torch.float32 and on cpu device.


### **Tensor attributes**

After creating a `tensor`, we can see some information about it using its attributes. Some of the attributes include size, data type, ndim etc:

In [19]:
m = torch.rand(5, 6)
m.dtype # This tells us that it is float32

torch.float32

In [20]:
m.device # This returns device on which the tensor is located. In this case cpu.

device(type='cpu')

In [21]:
m.shape # Tells us the rank or dimension of the tensor. Here it is 5 x 6.

torch.Size([5, 6])

In [22]:
m.ndim # Tells us it has 2 dimensions.

2

There are additional attributes like:


*   `requires_grad`
*   `grad`
*   `grad_fn`
*   `s_cuda`
*   `is_sparse`
*   `is_quantized`
*   `is_leaf`
*  `is_mkldnn`

Well no need to dig them now.



### **Create `tensor` like other `tensor`**

You may have a `tensor` and want to create another one like it. This is normally achieved with the `_like` suffix. For example, empty_like, ones_like, rand_like.

In [23]:
n = torch.rand(2, 3)
p = torch.rand_like(n)

print(f"The original \n {n} \n and its like \n {p}.")


The original 
 tensor([[0.2506, 0.3494, 0.5554],
        [0.2493, 0.4752, 0.6765]]) 
 and its like 
 tensor([[0.9079, 0.6944, 0.6524],
        [0.0581, 0.2402, 0.0714]]).


The aspect of **_like** here gives the new tensor same shape, dtype and ndim. That is structurally similar but not necessarily elementwise. That is, the elements will be different.

## **`Tensor` Operations**
Well our task is not only to create `tensor`, but to work with them. So, in this part, we will cover some of the `tensor` operations, in fact we did them earlier when we were using transforms from `torchvision`. Some of the operations we will do here include slicing portions of the data, combining `tensor`, spliting `tensor` and both simple and advanced operations on them.

### **Indexing `tensors`**

We can index `tensor` by using [ ]. Just like with numpy arrays. In this example, we create a `tensor` then extract the element in the second row and second column.

In [67]:
x = torch.tensor([[1, 2], [3, 4], [5, 6], [7, 8]])
print(x)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


Now to index number 4:

In [29]:
x.shape # Confirming the shape of the tensor

torch.Size([4, 2])

In [25]:
print(x[1, 1].item())

4


In [28]:
print(x[1][1].item()) # This can be indexed as so too.

4


To index number 7:

In [ ]:
print(x[3, 0].item())

7


In [32]:
print(x[3][0].item()) # the .item() helps to return the actual number and not tensor.

7


### **Slicing `tensors`**

We can slice `tensor` by using [ ]. Just like with numpy arrays. In this example, we create a `tensor` then slice a portion of it.

In [68]:
x.shape

torch.Size([4, 2])

In [70]:
x

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [71]:
x[:2, :] # Slices the first two rows and all columns.

tensor([[1, 2],
        [3, 4]])

In [73]:
x[1:3, :] # Slices from row index 1 to 3 and all columns.

tensor([[3, 4],
        [5, 6]])

In [74]:
x[:, 1] # All rows in column 1

tensor([2, 4, 6, 8])

In [82]:
x[:, 0] # All rows in column index 0

tensor([1, 3, 5, 7])

In [84]:
x[:, -1] # All rows in column 1

tensor([2, 4, 6, 8])

## **Exercises**

1. Create a tensor with random integers between 0 and 10 called `ten` of shape 5 by 7. Ensure the dtype is `int16`. Ensure you set manual seed, preferably **248** so that you get same answer as my `tensor`.
2. In the `ten` created, index element in row 3 column 4.
  * Print it as a `tensor`
  * print it as an item
3. Slice the `ten` from rows 3 to 4 and columns 4 to 6.

In [119]:
torch.manual_seed(248)
ten = torch.randint(low = 0, high = 10, size = (5, 7), dtype = torch.int16)
ten

tensor([[2, 7, 3, 0, 6, 7, 9],
        [5, 0, 0, 7, 4, 9, 7],
        [5, 1, 6, 7, 0, 0, 1],
        [9, 2, 0, 5, 9, 5, 5],
        [3, 5, 4, 1, 9, 0, 3]], dtype=torch.int16)

In [120]:
ten[2, 2]

tensor(6, dtype=torch.int16)

In [121]:
ten[2, 2].item()

6

In [122]:
ten[2:4, 3:6]

tensor([[7, 0, 0],
        [5, 9, 5]], dtype=torch.int16)

## **References**

https://pytorch.org/docs/stable/tensors.html

https://pytorch.org/tutorials/beginner/introyt/tensors_deeper_tutorial.html