<a href="https://colab.research.google.com/github/Wycology/deep_learning_course/blob/main/2_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <font color='green'><b> SATELLITE DATA FOR AGRICULTURAL ECONOMISTS</b></font>


<font color='blue'><b>THEORY AND PRACTICE</b></font>

**_MACHINE & DEEP LEARNING_**


*David Wuepper, Hadi Hadi, Wyclife Agumba Oluoch*

[Land Economics Group](https://www.ilr1.uni-bonn.de/en/research/research-groups/land-economics), University of Bonn, Bonn, Germany

---

# **Background**


---

`Tensor`, by definition, is the fundamental data structure used to store and manipulate data in `PyTorch`. Understanding `tensor` is paramount to understanding how `PyTorch` implements advanced functions for deep learning. At both preprocessing of input and postprocessing of output, you will be dealing with `tensor` in most cases. It is therefore important to understand what `tensor` are and operations on them. If you know `NumPy` then you are 100% good to take on `tensor`. Let us see how to create some `tensor`.

For us to have `tensor`, we need to load `PyTorch` library first.

In [2]:
import torch # Of course we need to have the PyTorch

We start with a simple `tensor` with just one digit.

# **Creating `tensor`**
---
In order to use a `tensor`, we need to create it. We can create a `tensor` easily using a `torch.empty()` function as follows:

In [5]:
x = torch.empty(2, 3) # Creates a tensor of shape 2 by 3, that is two rows and three columns.
print(x)

tensor([[5.4222e-35, 0.0000e+00, 1.6971e-33],
        [0.0000e+00, 1.1210e-43, 0.0000e+00]])


The `empty()` method comes pre-built in `PyTorch`. The created tensor is 2-dimensional, normally called 2-d `tensor`. This is because it has **two** rows and **three** columns. You might be wondering why we call it empty yet you see some values. It is empty in the sense that the values you see are actually what was in the memory of the computer when the empty `tensor` was allocated in memory. In reality, the `tensor` is empty and values can be fed into it. Note that sometimes a 1-dimensional `tensor` is called a _vector_, 2-dimensional `tensor` called a _matrix_, and the word `tensor` normally used when the dimensions are above 2. Anyway, all are `tensor`s.

As opposed to `empty` `tensor`, one would normally prefer to have some values in a created `tensor`. A `tensor` can be created with all its elements set to **zeros**, or **ones**, or some **random values** that can be integers or floats. Good enough, all these can be done by in-built methods in `PyTorch` as follows:



In [6]:
zeros_tensor = torch.zeros(2, 3) # This is tensor will all values set to zeros.
print(zeros_tensor)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [7]:
ones_tensor = torch.ones(2, 3) # This is tensor will all values set to ones.
print(ones_tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


<font color='red'><b>NOTE</b></font>: For the random `tensor`, it is a good practice to set **random seed** so that your output is reproducible the next time you rerun the same code. Remember to use the same integer values in the seed each time you want to reproduce the values.

In [14]:
torch.manual_seed(248) # This ensures that the code is reproducible.
random_tensor = torch.rand(2, 3) # This creates a tensor with random values between 0 and 1 in it.
print(random_tensor)

tensor([[0.1486, 0.6503, 0.1690],
        [0.0158, 0.4595, 0.9061]])


# **Shape of `tensor`**
---

When we want to perform some operations on a `tensor`, it is important to know its shape (printed out as **torch.Size([])**). This will tell us for example if the `tensor` is 1-dimensional, 2-d, 3-d, 4-d among others. There are some operations that we can only perform is specific rules of `tensor` shapes are obeyed as we will see. In order to know the shape of a tensor, we use the `shape` property as follows:

In [20]:
torch.manual_seed(248)
x = torch.rand(2, 3)
print(x.shape) # This is a two by three matrix.

torch.Size([2, 3])


You can think of the above matrix as a single band/image with two rows and three columns. Meaning this is basically having 6 elements inside it. We can print it as and confirm the number of elements in it as follows:

In [21]:
print(x)

tensor([[0.1486, 0.6503, 0.1690],
        [0.0158, 0.4595, 0.9061]])


Let us assume that you have an **RGB** image. That is, an image with three bands/color channels. In this casewe will have a 3-d `tensor`. This is becase we will have rows and columns as well as number of channels. Let us say, you have an RGB image of a cup with 256 pixels in row and 256 pixels in column for each of the three color channels. This will be something like (3, 256, 256). Let us create one:

In [25]:
torch.manual_seed(248)
rgb_tensor = torch.rand(3, 256, 256) # This is a 3-d tensor (channels dimension, rows dimension, and column dimension)
print(rgb_tensor.shape)

torch.Size([3, 256, 256])


The output is a list with 3, 256, and 256 elements in it corresponding to number of channels, rows and columns. The 3 means there are 3 elements in the first dimension. the first 256 means there are 256 elements in the second dimension and the last 256 means there are 256 elements in the third dimension.

In [26]:
print(rgb_tensor)

tensor([[[0.1486, 0.6503, 0.1690,  ..., 0.8042, 0.1762, 0.3878],
         [0.6061, 0.0266, 0.6565,  ..., 0.7283, 0.7022, 0.6209],
         [0.4686, 0.5914, 0.0205,  ..., 0.2622, 0.1006, 0.5342],
         ...,
         [0.4051, 0.9665, 0.9868,  ..., 0.6381, 0.9864, 0.7085],
         [0.6336, 0.8528, 0.4961,  ..., 0.6412, 0.6450, 0.5386],
         [0.3577, 0.7328, 0.4285,  ..., 0.2057, 0.8538, 0.1834]],

        [[0.1505, 0.2070, 0.0899,  ..., 0.9604, 0.4554, 0.2742],
         [0.0976, 0.9119, 0.0958,  ..., 0.3554, 0.9178, 0.1921],
         [0.6962, 0.9772, 0.1616,  ..., 0.8772, 0.3858, 0.0328],
         ...,
         [0.5004, 0.3803, 0.6465,  ..., 0.5358, 0.6438, 0.4367],
         [0.1902, 0.6078, 0.8052,  ..., 0.1226, 0.7050, 0.0753],
         [0.1047, 0.3733, 0.9489,  ..., 0.6650, 0.0291, 0.7273]],

        [[0.2848, 0.4889, 0.5891,  ..., 0.6803, 0.0650, 0.1653],
         [0.8378, 0.1194, 0.9079,  ..., 0.8441, 0.4194, 0.5504],
         [0.7955, 0.4902, 0.4107,  ..., 0.0283, 0.8470, 0.

## **Creating `tensor` _like**

There can be instances when you already have a tensor and you want to initialize another tensor **like** the one you have. The like here does not mean it will also have the same actual elements, but means will have same attributes including shape and data type. We will look at `tensor` data types later. Now, we can create a `tensor` like one we have but only filled with zeros, or empty, or ones, or random. The only think we need to remember from what we already discussed above is to add `_like` to the zeros, ones, rand as follows:

> Add blockquote



In [32]:
zeros_like_rgb = torch.zeros_like(rgb_tensor)
print(zeros_like_rgb.shape) # The shape is similar to that of rgb_tensor
print(zeros_like_rgb) # The values in it are, however, zeros

torch.Size([3, 256, 256])
tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]])


In [34]:
ones_like_rgb = torch.ones_like(rgb_tensor)
print(ones_like_rgb.shape) # The shape is the same as the shape of rgb_tensor ([3, 256, 256])
print(ones_like_rgb) # The elements in the output are all 1.'s

torch.Size([3, 256, 256])
tensor([[[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]]])


In [37]:
torch.manual_seed(248)
rand_like_rgb = torch.rand_like(rgb_tensor)
print(rand_like_rgb.shape) # Same shape as rgb_tensor
print(rand_like_rgb) # Interesting, the values here are exactly the same as those in rgb_tensor. Why? Because we used same manual seed.

torch.Size([3, 256, 256])
tensor([[[0.1486, 0.6503, 0.1690,  ..., 0.8042, 0.1762, 0.3878],
         [0.6061, 0.0266, 0.6565,  ..., 0.7283, 0.7022, 0.6209],
         [0.4686, 0.5914, 0.0205,  ..., 0.2622, 0.1006, 0.5342],
         ...,
         [0.4051, 0.9665, 0.9868,  ..., 0.6381, 0.9864, 0.7085],
         [0.6336, 0.8528, 0.4961,  ..., 0.6412, 0.6450, 0.5386],
         [0.3577, 0.7328, 0.4285,  ..., 0.2057, 0.8538, 0.1834]],

        [[0.1505, 0.2070, 0.0899,  ..., 0.9604, 0.4554, 0.2742],
         [0.0976, 0.9119, 0.0958,  ..., 0.3554, 0.9178, 0.1921],
         [0.6962, 0.9772, 0.1616,  ..., 0.8772, 0.3858, 0.0328],
         ...,
         [0.5004, 0.3803, 0.6465,  ..., 0.5358, 0.6438, 0.4367],
         [0.1902, 0.6078, 0.8052,  ..., 0.1226, 0.7050, 0.0753],
         [0.1047, 0.3733, 0.9489,  ..., 0.6650, 0.0291, 0.7273]],

        [[0.2848, 0.4889, 0.5891,  ..., 0.6803, 0.0650, 0.1653],
         [0.8378, 0.1194, 0.9079,  ..., 0.8441, 0.4194, 0.5504],
         [0.7955, 0.4902, 0.4107

## **Creating `tensor` directly from data**

It is also possible to directly supply data in `torch.tensor()` to create a `tensor` of your liking. The values can be a list, tuple, or numpy array etc.

In [44]:
some_values = torch.tensor([11, 2.0, 376, 0.004]) # Manually supplied values
print(some_values.shape) # This is a one dimension tensor.
print(some_values)

torch.Size([4])
tensor([1.1000e+01, 2.0000e+00, 3.7600e+02, 4.0000e-03])


In [43]:
some_values = torch.tensor([[1.2, 23, 13.1, 4.2], [23, 4, 5, 67]])
print(some_values.shape) # This is a two dimension tensor.
print(some_values)

torch.Size([2, 4])
tensor([[ 1.2000, 23.0000, 13.1000,  4.2000],
        [23.0000,  4.0000,  5.0000, 67.0000]])


In [46]:
tuple_tensor = torch.tensor((2.22, 1.675, 8)) # Creating from tuple
print(tuple_tensor.shape) # This is 1-d tensor
print(tuple_tensor)


torch.Size([3])
tensor([2.2200, 1.6750, 8.0000])


In [50]:
tuple_list_tensor = torch.tensor(((2.22, 1.675, 8), [1.2, 23, 13.1])) # From tuple and list
print(tuple_list_tensor.shape) # 2-d tensor
print(tuple_list_tensor)

torch.Size([2, 3])
tensor([[ 2.2200,  1.6750,  8.0000],
        [ 1.2000, 23.0000, 13.1000]])


<font color="red">**NOTE:**</font> Using `torch.tensor` creates a copy of the data. Sometimes this may overwhelm your computer memory. For example if you do it on 100 Tb of data you end up with over 200 Tb of data. <font color="orange">_Remember, `tensor` always occupies larger memory than array_.</font>

# **`Tensor` Data Types**
---

Data types such as **integer**, **float**, **boolean** among others can easily be set for `tensor`s during creation. This is often crucial as operations on `tensor`s can be strictly data type dependent. That is, some operations may only need the data type to be float32 and not integer.

In [54]:
int_tensor = torch.ones((2, 3), dtype=torch.int16) # Specifying the data type to torch.int16
print(int_tensor)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)


Notice that in the printout, dtype is also shown. This did not happen in our earlier tensors because we did not specify it during creation. Let us see the same `tensor` under float64.

In [59]:
float64_tensor = torch.ones((2, 3), dtype = torch.float64)
print(float64_tensor.shape) # Of course 2-d tensor with two rows and three columns.
print(float64_tensor) # The printout also shows the dtype.


torch.Size([2, 3])
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


Other than definition of the data type of a tensor during creation, we can also specify a data type to an existing `tensor`. Say, I created a `tensor` called **float64_tensor** above, and we now want it to be **float32_tensor**. We can achieve that using `.to()` method as follows:

In [61]:
float32_tensor = float64_tensor.to(torch.float32)
print(float32_tensor) # Now this is float32

tensor([[1., 1., 1.],
        [1., 1., 1.]])


Notice here that float32 is not printed as was float64. This is because it is the **default** data type. You can confirm this by using `.dtype` attribute on the `tensor`.

In [62]:
float32_tensor.dtype

torch.float32

The following is a list of **common** data types that you will encounter most of the times:
* torch.bool<font color="red">
+ torch.int8
+ torch.uint8
+ torch.int16
+ torch.int32
+ torch.int64</font><font color="magenta">
+ torch.half
+ torch.float
+ torch.double
+ torch.bfloat16


# **Some Math operations with `Tensors`**

We now know how to create `tensor`s and also know various data types they can take. Next is what can we do with the `tensors`? To begin with we will do some basic addition with `scalar`, like numbers. For example, if we have a `tensor` of ones and we want to add 5 to each of the elements in it.

In [63]:
ones_tensor = torch.ones(2, 3)
print(ones_tensor)

# Add 5 to each of the elements

five_added = ones_tensor + 5
print(five_added)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[6., 6., 6.],
        [6., 6., 6.]])


It is evident that the `scalar` 5 is added to each of the elements in our original `ones_tensor`. Likewise, we can multiply a `tensor` by a `scalar` quantity  as follows:

In [64]:
torch.manual_seed(248)
random_tensor = torch.rand(2, 3)
print(random_tensor)
multiplied_tensor = random_tensor * 5
print(multiplied_tensor)

tensor([[0.1486, 0.6503, 0.1690],
        [0.0158, 0.4595, 0.9061]])
tensor([[0.7429, 3.2515, 0.8448],
        [0.0788, 2.2977, 4.5307]])


We can also supply a a chain of arithmetic operations including division, multiplication, addition, subtraction by `scalars`  as follows

In [65]:
torch.manual_seed(248)
random_tensor = torch.rand(2, 3)
print(random_tensor)
chained_operations = (((random_tensor / 3) * 7) + 9) - 89
print(chained_operations)

tensor([[0.1486, 0.6503, 0.1690],
        [0.0158, 0.4595, 0.9061]])
tensor([[-79.6533, -78.4826, -79.6058],
        [-79.9632, -78.9277, -77.8857]])


Let us try to confirm one element. Say the first element which is 0.1486

In [66]:
0.1486 / 3 # First we divide it by 3

0.04953333333333334

In [67]:
0.04953333333333334 * 7 # Then we multiply by 7

0.3467333333333334

In [68]:
0.3467333333333334 + 9 # Then we add 9

9.346733333333333

In [69]:
9.346733333333333 - 89 # Finally we subtract 89

-79.65326666666667

In [ ]:
# Create from preexisting arrays
x = torch.tensor([1, 2, 3]) # Creating from a list
print(x)


tensor([1, 2, 3])


In [ ]:
x = torch.tensor((1, 2, 3)) # Creating from a tuple
print(x)

tensor([1, 2, 3])


In [ ]:
x = torch.tensor(numpy.array([1, 2, 3])) # Creating from numpy array
print(x)

tensor([1, 2, 3])


Other than `tensor` that we specifically indicate the values it should hold, we can also create `tensor` in which we only specify their dimensions/rank.

In [ ]:
w = torch.empty(2, 3) # Uninitialized, no one can predict the initial values
w

tensor([[5.4640e-05, 4.1296e-05, 2.1651e+23],
        [1.0979e-05, 3.1201e-18, 3.1360e+27]])

In [ ]:
w = torch.zeros(2, 3) # All elements in the tensor initialized by 0.0
w

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
w = torch.ones(2, 3) # All elements initialized by 1.0
w

tensor([[1., 1., 1.],
        [1., 1., 1.]])

Sometimes we may want to initialize a `tensor` with random numbers. There are functions that can help us with such tasks as follows:

In [ ]:
y = torch.rand(4, 5) # Creates a 4 x 5 tensor with elements from uniform distribution on the interval (0, 1)
y

tensor([[0.8418, 0.3298, 0.9768, 0.0707, 0.3640],
        [0.6385, 0.9551, 0.2330, 0.7469, 0.8732],
        [0.1216, 0.6281, 0.0420, 0.3550, 0.3747],
        [0.2140, 0.1895, 0.3865, 0.5344, 0.3880]])

In [ ]:
y = torch.randn(4, 5) # Creates a 4 x 5 tensor with elements from normal distribution with mean 0 and variance of 1.
y

tensor([[-1.3413,  0.7833, -0.2912,  0.4531,  0.4691],
        [ 0.9453, -1.1535,  0.5099, -0.8825, -1.1839],
        [-1.6739,  0.3192,  0.4024,  0.1985, -1.4034],
        [ 0.0345,  0.6887,  1.1673,  0.2618,  0.8854]])

In [ ]:
y = torch.randint(-5, 5, (2, 3)) # Creates a 2 x 3 tensor with elements drawn between 0 and 9
y

tensor([[ 4, -4, -4],
        [ 3,  3,  2]])

### **Data type and device**

Upon creating the `tensor`, it is possible and sometimes a good practice to assign them data type and device. This can be achieved as follows:

In [ ]:
m = torch.rand((2, 3), dtype = torch.float32, device = 'cpu')
print(f"The tensor is of data type: {m.dtype} and on {m.device} device.")

The tensor is of data type: torch.float32 and on cpu device.


### **Tensor attributes**

After creating a `tensor`, we can see some information about it using its attributes. Some of the attributes include size, data type, ndim etc:

In [ ]:
m = torch.rand(5, 6)
m.dtype # This tells us that it is float32

torch.float32

In [ ]:
m.device # This returns device on which the tensor is located. In this case cpu.

device(type='cpu')

In [ ]:
m.shape # Tells us the rank or dimension of the tensor. Here it is 5 x 6.

torch.Size([5, 6])

In [ ]:
m.ndim # Tells us it has 2 dimensions.

2

There are additional attributes like:


*   `requires_grad`
*   `grad`
*   `grad_fn`
*   `s_cuda`
*   `is_sparse`
*   `is_quantized`
*   `is_leaf`
*  `is_mkldnn`

Well no need to dig them now.



### **Create `tensor` like other `tensor`**

You may have a `tensor` and want to create another one like it. This is normally achieved with the `_like` suffix. For example, empty_like, ones_like, rand_like.

In [ ]:
n = torch.rand(2, 3)
p = torch.rand_like(n)

print(f"The original \n {n} \n and its like \n {p}.")


The original 
 tensor([[0.2506, 0.3494, 0.5554],
        [0.2493, 0.4752, 0.6765]]) 
 and its like 
 tensor([[0.9079, 0.6944, 0.6524],
        [0.0581, 0.2402, 0.0714]]).


The aspect of **_like** here gives the new tensor same shape, dtype and ndim. That is structurally similar but not necessarily elementwise. That is, the elements will be different.

## **`Tensor` Operations**
Well our task is not only to create `tensor`, but to work with them. So, in this part, we will cover some of the `tensor` operations, in fact we did them earlier when we were using transforms from `torchvision`. Some of the operations we will do here include slicing portions of the data, combining `tensor`, spliting `tensor` and both simple and advanced operations on them.

### **Indexing `tensors`**

We can index `tensor` by using [ ]. Just like with numpy arrays. In this example, we create a `tensor` then extract the element in the second row and second column.

In [ ]:
x = torch.tensor([[1, 2], [3, 4], [5, 6], [7, 8]])
print(x)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


Now to index number 4:

In [ ]:
x.shape # Confirming the shape of the tensor

torch.Size([4, 2])

In [ ]:
print(x[1, 1].item())

4


In [ ]:
print(x[1][1].item()) # This can be indexed as so too.

4


To index number 7:

In [ ]:
print(x[3, 0].item())

7


In [ ]:
print(x[3][0].item()) # the .item() helps to return the actual number and not tensor.

7


### **Slicing `tensors`**

We can slice `tensor` by using [ ]. Just like with numpy arrays. In this example, we create a `tensor` then slice a portion of it.

In [ ]:
x.shape

torch.Size([4, 2])

In [ ]:
x

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [ ]:
x[:2, :] # Slices the first two rows and all columns.

tensor([[1, 2],
        [3, 4]])

In [ ]:
x[1:3, :] # Slices from row index 1 to 3 and all columns.

tensor([[3, 4],
        [5, 6]])

In [ ]:
x[:, 1] # All rows in column 1

tensor([2, 4, 6, 8])

In [ ]:
x[:, 0] # All rows in column index 0

tensor([1, 3, 5, 7])

In [ ]:
x[:, -1] # All rows in column 1

tensor([2, 4, 6, 8])

## **Exercises**

1. Create a tensor with random integers between 0 and 10 called `ten` of shape 5 by 7. Ensure the dtype is `int16`. Ensure you set manual seed, preferably **248** so that you get same answer as my `tensor`.
2. In the `ten` created, index element in row 3 column 4.
  * Print it as a `tensor`
  * print it as an item
3. Slice the `ten` from rows 3 to 4 and columns 4 to 6.

In [ ]:
torch.manual_seed(248)
ten = torch.randint(low = 0, high = 10, size = (5, 7), dtype = torch.int16)
ten

tensor([[2, 7, 3, 0, 6, 7, 9],
        [5, 0, 0, 7, 4, 9, 7],
        [5, 1, 6, 7, 0, 0, 1],
        [9, 2, 0, 5, 9, 5, 5],
        [3, 5, 4, 1, 9, 0, 3]], dtype=torch.int16)

In [ ]:
ten[2, 2]

tensor(6, dtype=torch.int16)

In [ ]:
ten[2, 2].item()

6

In [ ]:
ten[2:4, 3:6]

tensor([[7, 0, 0],
        [5, 9, 5]], dtype=torch.int16)

## **References**

https://pytorch.org/docs/stable/tensors.html

https://pytorch.org/tutorials/beginner/introyt/tensors_deeper_tutorial.html