<a href="https://colab.research.google.com/github/Wycology/deep_learning_course/blob/main/2_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <font color='green'><b> SATELLITE DATA FOR AGRICULTURAL ECONOMISTS</b></font>


<font color='blue'><b>THEORY AND PRACTICE</b></font>

**_MACHINE & DEEP LEARNING_**


*David Wuepper, Hadi Hadi, Wyclife Agumba Oluoch*

[Land Economics Group](https://www.ilr1.uni-bonn.de/en/research/research-groups/land-economics), University of Bonn, Bonn, Germany

---

# **Background**


---

`Tensor`, by definition, is the fundamental data structure used to store and manipulate data in `PyTorch`. Understanding `tensor` is paramount to understanding how `PyTorch` implements advanced functions for deep learning. At both preprocessing of input and postprocessing of output, you will be dealing with `tensor` in most cases. It is therefore important to understand what `tensor` are and operations on them. If you know `NumPy` then you are 100% good to take on `tensor`. Let us see how to create some `tensor`.

For us to have `tensor`, we need to load `PyTorch` library first.

In [2]:
import torch # Of course we need to have the PyTorch

We start with a simple `tensor` with just one digit.

In [3]:
x = torch.tensor(2) # Creates a tensor containing value 2.
x

tensor(2)

We can also create a `tensor` from a list of numbers as follows.

In [4]:
x = torch.tensor([1, 2, 3]) # Creates a tensor containing the values 1, 2, and 3 in the list.
x

tensor([1, 2, 3])

We can have `tensor` for list within list.

In [5]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]]) # Creates a 2 x 3 tensor.
x

tensor([[1, 2, 3],
        [4, 5, 6]])

We can also perform simple operations with `tensor` like addition.

In [6]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
y = torch.tensor([[7, 8, 9], [10, 11, 12]])
z = x + y
print(z)

tensor([[ 8, 10, 12],
        [14, 16, 18]])


We may be interested in knowing the shape of the `tensor`.

In [7]:
print(z.shape)

torch.Size([2, 3])


## **Creating tensor**

`torch.tensor` is the basic way to create the `tensor` data structure. However, there are many ways to achieve this as follows:

In [8]:
import numpy # We are importing this because we will create some tensors from numpy

In [9]:
# Create from preexisting arrays
x = torch.tensor([1, 2, 3]) # Creating from a list
print(x)


tensor([1, 2, 3])


In [10]:
x = torch.tensor((1, 2, 3)) # Creating from a tuple
print(x)

tensor([1, 2, 3])


In [11]:
x = torch.tensor(numpy.array([1, 2, 3])) # Creating from numpy array
print(x)

tensor([1, 2, 3])


Other than `tensor` that we specifically indicate the values it should hold, we can also create `tensor` in which we only specify their dimensions/rank.

In [12]:
w = torch.empty(2, 3) # Uninitialized, no one can predict the initial values
w

tensor([[0.0000e+00, 0.0000e+00, 7.7052e+31],
        [7.2148e+22, 1.5766e-19, 1.0256e-08]])

In [13]:
w = torch.zeros(2, 3) # All elements in the tensor initialized by 0.0
w

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [14]:
w = torch.ones(2, 3) # All elements initialized by 1.0
w

tensor([[1., 1., 1.],
        [1., 1., 1.]])

Sometimes we may want to initialize a `tensor` with random numbers. There are functions that can help us with such tasks as follows:

In [15]:
y = torch.rand(4, 5) # Creates a 4 x 5 tensor with elements from uniform distribution on the interval (0, 1)
y

tensor([[0.0386, 0.7281, 0.1284, 0.9974, 0.5955],
        [0.9195, 0.0446, 0.1788, 0.6253, 0.6133],
        [0.3281, 0.8437, 0.2980, 0.5530, 0.8219],
        [0.6243, 0.4149, 0.4612, 0.5509, 0.1310]])

In [16]:
y = torch.randn(4, 5) # Creates a 4 x 5 tensor with elements from normal distribution with mean 0 and variance of 1.
y

tensor([[ 0.6073,  1.3518, -0.2577,  0.0061,  1.5835],
        [ 0.3248,  0.8622, -0.4051, -0.0706, -0.5016],
        [ 0.2374, -1.8714,  1.7714,  0.5730,  0.5687],
        [ 0.9565,  0.1139, -0.8358, -1.4239, -0.4171]])

In [18]:
y = torch.randint(-5, 5, (2, 3)) # Creates a 2 x 3 tensor with elements drawn between 0 and 9
y

tensor([[ 4,  0, -1],
        [-4, -4,  4]])

### **Data type and device**

Upon creating the `tensor`, it is possible and sometimes a good practice to assign them data type and device. This can be achieved as follows:

In [22]:
m = torch.rand((2, 3), dtype = torch.float32, device = 'cpu')
print(f"The tensor is of data type: {m.dtype} and on {m.device} device.")

The tensor is of data type: torch.float32 and on cpu device.


### **Tensor attributes**

After creating a `tensor`, we can see some information about it using its attributes. Some of the attributes include size, data type, ndim etc:

In [23]:
m = torch.rand(5, 6)
m.dtype # This tells us that it is float32

torch.float32

In [24]:
m.device # This returns device on which the tensor is located. In this case cpu.

device(type='cpu')

In [25]:
m.shape # Tells us the rank or dimension of the tensor. Here it is 5 x 6.

torch.Size([5, 6])

In [26]:
m.ndim # Tells us it has 2 dimensions.

2

There are additional attributes like:


*   `requires_grad`
*   `grad`
*   `grad_fn`
*   `s_cuda`
*   `is_sparse`
*   `is_quantized`
*   `is_leaf`
*  `is_mkldnn`

Well no need to dig them now.



### **Create `tensor` like other `tensor`**

You may have a `tensor` and want to create another one like it. This is normally achieved with the `_like` suffix. For example, empty_like, ones_like, rand_like.

In [27]:
n = torch.rand(2, 3)
p = torch.rand_like(n)

print(f"The original \n {n} \n and its like \n {p}.")


The original 
 tensor([[0.6909, 0.8130, 0.6849],
        [0.1310, 0.4277, 0.1645]]) 
 and its like 
 tensor([[0.3612, 0.3122, 0.4362],
        [0.7410, 0.9626, 0.6022]]).


The aspect of **_like** here gives the new tensor same shape, dtype and ndim. That is structurally similar but not necessarily elementwise. That is, the elements will be different.

## **`Tensor` Operations**
Well our task is not only to create `tensor`, but to work with them. So, in this part, we will cover some of the `tensor` operations, in fact we did them earlier when we were using transforms from `torchvision`. Some of the operations we will do here include slicing portions of the data, combining `tensor`, spliting `tensor` and both simple and advanced operations on them.

### **Indexing `tensors`**

We can index `tensor` by using [ ]. Just like with numpy arrays. In this example, we create a `tensor` then extract the element in the second row and second column.

In [28]:
x = torch.tensor([[1, 2], [3, 4], [5, 6], [7, 8]])
print(x)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


Now to index number 4:

In [29]:
print(x[1, 1].item())

4


To index number 7:

In [30]:
print(x[3, 0].item())

7


In [32]:
x.shape

torch.Size([4, 2])

In [31]:
# Slice 1,2,3 and 4
x[:1, :1]

tensor([[1]])