<a href="https://colab.research.google.com/github/Wycology/deep_learning_course/blob/main/2_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **SATELLITE DATA FOR AGRICULTURAL ECONOMISTS**


**THEORY AND PRACTICE**

**_MACHINE & DEEP LEARNING_**


*David Wuepper, Hadi Hadi, Wyclife Agumba Oluoch*

---

# **Background**


---

Tensor, by definition, is the fundamental data structure used to store and manipulate data. Understanding tensor is paramount to understanding how pytorch implements advanced functions for deep learning. At both preprocessing of input and postprocessing of output, you will be dealing with tensors in most cases. It is therefore important to understand what tensors are and operations on them. If you know Numpy then you are almost 100% good to take on tensors. Let us see how to create some tensors.

For us to have tensor, we need to load pytorch library first.

In [ ]:
import torch # Of course we need to have the pytorch

We start with a simple tensor with just one digit.

In [ ]:
x = torch.tensor(2) # Creates a tensor containing value 2.
x

tensor(2)

We can also create a tensor from a list of numbers as follows.

In [ ]:
x = torch.tensor([1, 2, 3]) # Creates a tensor containing the values 1, 2, and 3 in the list.
x

tensor([1, 2, 3])

We can have tensor for list within list.

In [ ]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]]) # Creates a 2 x 3 tensor.
x

tensor([[1, 2, 3],
        [4, 5, 6]])

We can also perform simple operation with tensor like addition.

In [ ]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
y = torch.tensor([[7, 8, 9], [10, 11, 12]])
z = x + y
print(z)

tensor([[ 8, 10, 12],
        [14, 16, 18]])


We may be interested in knowing the shape of the tensor.

In [ ]:
print(z.shape)

torch.Size([2, 3])


## **Creating tensor**

`torch.tensor` is the basic way to create the tensor data structure. However, there are many ways to achieve this as follows:

In [ ]:
import numpy # We are importing this because we will create some tensors from numpy

In [ ]:
# Create from preexisting arrays
x = torch.tensor([1, 2, 3]) # Creating from a list
print(x)


tensor([1, 2, 3])


In [ ]:
x = torch.tensor((1, 2, 3)) # Creating from a tuple
print(x)

tensor([1, 2, 3])


In [ ]:
x = torch.tensor(numpy.array([1, 2, 3])) # Creating from numpy array
print(x)

tensor([1, 2, 3])


Other than tensors that we specifically indicate the values it should hold, we can also create tensors in which we only specify their dimensions/rank.

In [ ]:
w = torch.empty(2, 3) # Uninitialized, no one can predict the initial values
w

tensor([[0.0000e+00, 4.3288e-41, 7.7052e+31],
        [7.2148e+22, 1.5766e-19, 1.0256e-08]])

In [ ]:
w = torch.zeros(2, 3) # All elements in the tensor initialized by 0.0
w

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
w = torch.ones(2, 3) # All elements initialized by 1.0
w

tensor([[1., 1., 1.],
        [1., 1., 1.]])

Sometimes we may want to initialize a tensor with random numbers. There are functions that can help us with such tasks as follows:

In [ ]:
y = torch.rand(4, 5) # Creates a 4 x 5 tensor with elements from uniform distribution on the interval (0, 1)
y

tensor([[0.1717, 0.5258, 0.3618, 0.7427, 0.2994],
        [0.9323, 0.5637, 0.8811, 0.5929, 0.9866],
        [0.0910, 0.6652, 0.2984, 0.3618, 0.5628],
        [0.6690, 0.6747, 0.9818, 0.0238, 0.3912]])

In [ ]:
y = torch.randn(4, 5) # Creates a 4 x 5 tensor with elements from normal distribution with mean 0 and variance of 1.
y

tensor([[ 1.3488, -1.4248, -1.7881, -2.6139, -0.4134],
        [-1.0375, -0.2330, -0.2311, -0.2198,  1.3322],
        [-0.5642,  2.1297,  0.3767,  1.9260,  0.0082],
        [ 0.3363,  0.3728, -0.5024, -0.7766, -1.7537]])

In [ ]:
y = torch.randint(-5, 5, (2, 3)) # Creates a 2 x 3 tensor with elements drawn between 0 and 9
y

tensor([[ 1,  0,  2],
        [ 4, -1,  4]])

### **Data type and device**

Upon creating the tensors, it is possible and sometimes a good practice to assign them data type and device. This can be achieved as follows:

In [ ]:
m = torch.rand((2, 3), dtype = torch.float32, device = 'cpu')
print(f"The tensor is of data type: {m.dtype} and on {m.device} device.")

The tensor is of data type: torch.float32 and on cpu device.


### **Tensor attributes**

After creating a tensor, we can see some information about it using its attributes. Some of the attributes include size, data type, ndim etc:

In [ ]:
m = torch.rand(5, 6)
m.dtype # This tells us that it is float32

torch.float32

In [ ]:
m.device # This returns device on which the tensor is located. In this case cpu.

device(type='cpu')

In [ ]:
m.shape # Tells us the rank or dimension of the tensor. Here it is 5 x 6.

torch.Size([5, 6])

In [ ]:
m.ndim # Tells us it has 2 dimensions.

2

There are additional attributes like:


*   `requires_grad`
*   `grad`
*   `grad_fn`
*   `s_cuda`
*   `is_sparse`
*   `is_quantized`
*   `is_leaf`
*  `is_mkldnn`

Well no need to dig them now.



### **Create tensor like other tensor**

You may have one tensor and want to create another one like it. This is normally achieved with the `_like` suffix. For example, empty_like, ones_like, rand_like.

In [ ]:
n = torch.rand(2, 3)
p = torch.rand_like(n)

print(f"The original \n {n} \n and its like \n {p}.")


The original 
 tensor([[0.0654, 0.3856, 0.6090],
        [0.0187, 0.6504, 0.5025]]) 
 and its like 
 tensor([[0.1456, 0.6283, 0.3885],
        [0.6660, 0.3315, 0.8858]]).


The aspect of _like here gives the new tensor same shape, dtype and ndim. That is structurally similar but not necessarily elementwise. That is, the elements will be different.

## **Tensor Operations**
Well our task is not only to create tensors, but to work with them. So, in this part, we will cover some of the tensor operations, in fact we did them earlier when we were using transforms from `torchvision`. Some of the operations we will do here include slicing portions of the data, combining tensors, spliting tensors and both simple and advanced operations on them.

### **Indexing tensors**

We can index tensors by using [ ]. Just like with numpy arrays. In this example, we create a tensor then extract the element in the second row and second column.

In [ ]:
x = torch.tensor([[1, 2], [3, 4], [5, 6], [7, 8]])
print(x)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


Now to index number 4:

In [ ]:
print(x[1, 1].item())

4


To index number 7:

In [ ]:
print(x[3, 0].item())

7
