<a href="https://colab.research.google.com/github/Wycology/deep_learning_course/blob/main/2_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **SATELLITE DATA FOR AGRICULTURAL ECONOMISTS**


**THEORY AND PRACTICE**

**_MACHINE & DEEP LEARNING_**


*David Wuepper, Hadi Hadi, Wyclife Agumba Oluoch*

---

# **Background**


---

Tensor, by definition, is the fundamental data structure used to store and manipulate data. Understanding tensor is paramount to understanding how pytorch implements advanced functions for deep learning. At both preprocessing of input and postprocessing of output, you will be dealing with tensors in most cases. It is therefore important to understand what tensors are and operations on them. If you know Numpy then you are almost 100% good to take on tensors. Let us see how to create some tensors.

For us to have tensor, we need to load pytorch library first.

In [1]:
import torch # Of course we need to have the pytorch

We start with a simple tensor with just one digit.

In [3]:
x = torch.tensor(2) # Creates a tensor containing value 2.
x

tensor(2)

We can also create a tensor from a list of numbers as follows.

In [5]:
x = torch.tensor([1, 2, 3]) # Creates a tensor containing the values 1, 2, and 3 in the list.
x

tensor([1, 2, 3])

We can have tensor for list within list.

In [6]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]]) # Creates a 2 x 3 tensor.
x

tensor([[1, 2, 3],
        [4, 5, 6]])

We can also perform simple operation with tensor like addition.

In [7]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
y = torch.tensor([[7, 8, 9], [10, 11, 12]])
z = x + y
print(z)

tensor([[ 8, 10, 12],
        [14, 16, 18]])


We may be interested in knowing the shape of the tensor.

In [8]:
print(z.shape)

torch.Size([2, 3])


## **Creating tensor**

`torch.tensor` is the basic way to create the tensor data structure. However, there are many ways to achieve this as follows:

In [9]:
import numpy # We are importing this because we will create some tensors from numpy

In [12]:
# Create from preexisting arrays
x = torch.tensor([1, 2, 3]) # Creating from a list
print(x)


tensor([1, 2, 3])


In [13]:
x = torch.tensor((1, 2, 3)) # Creating from a tuple
print(x)

tensor([1, 2, 3])


In [14]:
x = torch.tensor(numpy.array([1, 2, 3])) # Creating from numpy array
print(x)

tensor([1, 2, 3])


Other than tensors that we specifically indicate the values it should hold, we can also create tensors in which we only specify their dimensions/rank.

In [16]:
w = torch.empty(2, 3) # Uninitialized, no one can predict the initial values
w

tensor([[0.0000e+00, 4.3288e-41, 7.7052e+31],
        [7.2148e+22, 1.5766e-19, 1.0256e-08]])

In [18]:
w = torch.zeros(2, 3) # All elements in the tensor initialized by 0.0
w

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [19]:
w = torch.ones(2, 3) # All elements initialized by 1.0
w

tensor([[1., 1., 1.],
        [1., 1., 1.]])

Sometimes we may want to initialize a tensor with random numbers. There are functions that can help us with such tasks as follows:

In [33]:
y = torch.rand(4, 5) # Creates a 4 x 5 tensor with elements from uniform distribution on the interval (0, 1)
y

tensor([[0.1717, 0.5258, 0.3618, 0.7427, 0.2994],
        [0.9323, 0.5637, 0.8811, 0.5929, 0.9866],
        [0.0910, 0.6652, 0.2984, 0.3618, 0.5628],
        [0.6690, 0.6747, 0.9818, 0.0238, 0.3912]])

In [21]:
y = torch.randn(4, 5)
y

tensor([[ 1.3488, -1.4248, -1.7881, -2.6139, -0.4134],
        [-1.0375, -0.2330, -0.2311, -0.2198,  1.3322],
        [-0.5642,  2.1297,  0.3767,  1.9260,  0.0082],
        [ 0.3363,  0.3728, -0.5024, -0.7766, -1.7537]])

In [26]:
y = torch.randint(0, 9, (2, 3))
y

tensor([[1, 8, 0],
        [6, 5, 6]])